### ISSUE TITLE
Should weak functions be put into a separate file?

### ISSUE THREAD

**Issue by 9Fingered** [FSMLang/FSMLang#104]
The issue is that ld seems to link the weak function if it is in the same file, even though another file provides a non-weak version.  Would the weak versions still be taken if that .o is listed before the .o containing the non weak function?  Inquiring minds want to know!

Including weak functions when not appropriate messes up the multi-variant test strategy of looking for identical full test output from any of the -tc, -ts, and -te options.

**Comment by Jasinsky** [comment]
ChatGPT:
Yes, the ability to override a weak function in C is link order dependent. The order in which object files and libraries are linked can affect whether a weak function is overridden by a strong definition. This behavior is primarily influenced by the way the linker resolves symbols during the linking process. Here’s how link order plays a role:

Link Order and Symbol Resolution
Symbol Resolution: During linking, the linker processes object files and libraries in the order they are specified on the command line. When it encounters a weak symbol, it notes its presence but continues to search for a strong definition.

First Definition Wins: If a strong definition (non-weak) of a function is encountered, it overrides any weak definitions seen so far. The linker will use this strong definition for all references to that function.

Subsequent Definitions Ignored: Once a strong definition is found, any subsequent weak or strong definitions are ignored for that symbol. This means if you have a weak function in a library and a strong function in your object files, the strong function must appear in the link order before the weak function for the override to work correctly.
----------------------------------------------------------
I would retire this feature - or think about alternative implementation - sadly, only one which comes to my mind is runtime - aybe struct of f-ptrs pointing to the same action and then user substitutes on demand.

**Comment by 9Fingered** [comment]
@Jasinsky - accepting your suggestion to retire the issue.
