### ISSUE TITLE
Cannot change the name of the function to pass shared events.

### ISSUE THREAD

**Issue by jpsanford** [FSMLang/FSMLang#105]
The function auto-generated by FSMLang for passing shared events has different names for the output and input values based on the FSM machine name but it doesn't seem to be possible to change the name of the actual function which is always "pass_shared_event".

**Example:**

_MACHINE1_EVENT pass_shared_event(pMACHINE1 pfsm, pMACHINE1_SHARED_EVENT_STR sharer_list[])_
_MACHINE2_EVENT pass_shared_event(pMACHINE2 pfsm, pMACHINE2_SHARED_EVENT_STR sharer_list[])_

This isn't a problem if there is only a single parent FSM in the system but if there are multiple parent FSMs, there will be multiple definitions of the _pass_shared_event()_ function.

**Comment by 9Fingered** [comment]
As a workaround, add

`#define pass_shared_event machine1_pass_shared_event`

To the native block of machine 1 and a similar line to machine 2.

**Comment by 9Fingered** [comment]
This function name was changed to include the machine name in FSMLang version 1.42.  Please verify that the behavior is as needed with that version or later.

**Comment by jpsanford** [comment]
I tried the FSMLang version 1.43.1 release and it does generate a unique name for the pass_shared_event routine based on the machine name.  Thank you for looking into the issue.
