### ISSUE TITLE
Clarify license of generated code

### ISSUE THREAD

**Issue by bram-arcsec** [FSMLang/FSMLang#118]
Thanks for developing this tool and making it open source! Would it be possible to add a note to the repository if the GPL2 license also applies to the generated code or if it is exempt from the license requirements?

**Comment by 9Fingered** [comment]
Hello, @bram-arcsec  -  Thank you for your use of the tool!  Such a note will be added!

While you wait, you can take this note as your assurance that FSMLang claims no ownership of any kind over the generated code.

**Comment by bram-arcsec** [comment]
Thanks @9Fingered, greatly appreciated!
