### ISSUE TITLE
transition keyword sometimes mistaken for sub-machine

### ISSUE THREAD

**Issue by 9Fingered** [FSMLang/FSMLang#6]
When the transition keyword immediately follows the event and state lists, the parser thinks a sub-machine exists.

**Comment by Jasinsky** [comment]
Is this corresponding with -> https://github.com/FSMLang/FSMLang/issues/21

**Comment by 9Fingered** [comment]
There was no parsing error; rather, in this situation, an empty machine_list was incorrectly created, making it appear that sub-machines existed.
