### ISSUE TITLE
Build system dependency management

### ISSUE THREAD

**Issue by Jasinsky** [FSMLang/FSMLang#8]
Currently, the build system notifies about the lack of generated code header - i.e.
```
../src/fsm_cswitch.c:52:10: fatal error: y.tab.h: No such file or directory
   52 | #include "y.tab.h"

```

Build completes - but such warnings or errors may be confusing for new contributors or end users.

**Comment by 9Fingered** [comment]
-MG was added to the command line for dependency generation (depend.mk).
