### ISSUE TITLE
Generate a formatted cross reference table for FSM events

### ISSUE THREAD

**Issue by srrajendran** [FSMLang/FSMLang#85]
Generate a formatted file that contains cross reference table for FSM events (index/name)
programable format will be helpful to parse:
- JSON - key/value(index and event name) OR
- CSV

**Comment by 9Fingered** [comment]
Hello, @srrajendran -

Is this legal JSON?

"event_xrefs":[
  { "index": "0", "name": "top_e1" }
, { "index": "1", "name": "top_noEvent" }
, { "index": "2", "name": "top_numEvents" }
, { "index": "3", "name": "top_sub1_e1" }
, { "index": "4", "name": "top_sub2_e1" }
, { "index": "5", "name": "top_sub2_sub2Sub1_e1" }
, { "index": "6", "name": "top_numAllEvents" }
]

**Comment by srrajendran** [comment]
yes - just missing the outer most curly braces  to make it true JSON.
{
  "event_xrefs": [
    {
      "index": "0",
      "name": "top_e1"
    },
    {
      "index": "1",
      "name": "top_noEvent"
    },
    {
      "index": "2",
      "name": "top_numEvents"
    },
    {
      "index": "3",
      "name": "top_sub1_e1"
    },
    {
      "index": "4",
      "name": "top_sub2_e1"
    },
    {
      "index": "5",
      "name": "top_sub2_sub2Sub1_e1"
    },
    {
      "index": "6",
      "name": "top_numAllEvents"
    }
  ]
}
