### ISSUE TITLE
reStructuredText FSMLang output

### ISSUE THREAD

**Issue by Jasinsky** [FSMLang/FSMLang#93]
reStructuredText is used as an input language for popular documentation generator - Sphinx.
It would be nice to generate output similiar to HTML output - but in .rst format.

https://www.sphinx-doc.org/en/master/
https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html

**Comment by 9Fingered** [comment]
@Jasinsky - Should FSMLang create the conf.py file, or should we expect that to be done already?

**Comment by 9Fingered** [comment]
@Jasinsky  - Also, if the machine is to be documented as part of a larger document set, FSMLang should not generated index.rst, but then might need some help to understand how to fit into the document set.
